/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.Polinomios.Vista;

/**
 *
 * @author marioh.ramirez
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIngresoPolinomio2 = new javax.swing.JPanel();
        labelPolinomioIngreso2 = new javax.swing.JLabel();
        campoPolinomio2 = new javax.swing.JTextField();
        botonIngreso2 = new javax.swing.JButton();
        panelIngresoPolinomio1 = new javax.swing.JPanel();
        labelPolinomioIngreso1 = new javax.swing.JLabel();
        botonPolinomio1 = new javax.swing.JButton();
        campoPolinomio1 = new javax.swing.JTextField();
        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelPolinomio1 = new javax.swing.JPanel();
        labelPolinomio1 = new javax.swing.JLabel();
        panelPolinomio2 = new javax.swing.JPanel();
        labelPolinomio2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frameInicio"); // NOI18N
        setResizable(false);

        panelIngresoPolinomio2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingreso segundo polinomio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        labelPolinomioIngreso2.setText("Polinomio 2:");

        botonIngreso2.setText("Ingresar");
        botonIngreso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngreso2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIngresoPolinomio2Layout = new javax.swing.GroupLayout(panelIngresoPolinomio2);
        panelIngresoPolinomio2.setLayout(panelIngresoPolinomio2Layout);
        panelIngresoPolinomio2Layout.setHorizontalGroup(
            panelIngresoPolinomio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresoPolinomio2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPolinomioIngreso2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoPolinomio2)
                .addContainerGap())
            .addGroup(panelIngresoPolinomio2Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(botonIngreso2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelIngresoPolinomio2Layout.setVerticalGroup(
            panelIngresoPolinomio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresoPolinomio2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelIngresoPolinomio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPolinomioIngreso2)
                    .addComponent(campoPolinomio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonIngreso2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelIngresoPolinomio1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingreso primer polinomio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        labelPolinomioIngreso1.setText("Polinomio 1:");

        botonPolinomio1.setText("Ingresar");
        botonPolinomio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPolinomio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIngresoPolinomio1Layout = new javax.swing.GroupLayout(panelIngresoPolinomio1);
        panelIngresoPolinomio1.setLayout(panelIngresoPolinomio1Layout);
        panelIngresoPolinomio1Layout.setHorizontalGroup(
            panelIngresoPolinomio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresoPolinomio1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPolinomioIngreso1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoPolinomio1)
                .addContainerGap())
            .addGroup(panelIngresoPolinomio1Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(botonPolinomio1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        panelIngresoPolinomio1Layout.setVerticalGroup(
            panelIngresoPolinomio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresoPolinomio1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelIngresoPolinomio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPolinomioIngreso1)
                    .addComponent(campoPolinomio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonPolinomio1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        labelTitulo.setFont(new java.awt.Font("Droid Serif", 1, 48)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(154, 27, 27));
        labelTitulo.setText("Operaciones con Polinomios");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(labelTitulo)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelTitulo)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panelPolinomio1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Polinomio 1", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        labelPolinomio1.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        labelPolinomio1.setForeground(new java.awt.Color(86, 191, 115));
        labelPolinomio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPolinomio1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelPolinomio1Layout = new javax.swing.GroupLayout(panelPolinomio1);
        panelPolinomio1.setLayout(panelPolinomio1Layout);
        panelPolinomio1Layout.setHorizontalGroup(
            panelPolinomio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPolinomio1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPolinomio1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPolinomio1Layout.setVerticalGroup(
            panelPolinomio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPolinomio1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPolinomio1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPolinomio2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Polinomio 2", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        labelPolinomio2.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        labelPolinomio2.setForeground(new java.awt.Color(86, 191, 115));
        labelPolinomio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPolinomio2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelPolinomio2Layout = new javax.swing.GroupLayout(panelPolinomio2);
        panelPolinomio2.setLayout(panelPolinomio2Layout);
        panelPolinomio2Layout.setHorizontalGroup(
            panelPolinomio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPolinomio2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPolinomio2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPolinomio2Layout.setVerticalGroup(
            panelPolinomio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPolinomio2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPolinomio2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelPolinomio2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(panelIngresoPolinomio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panelIngresoPolinomio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(panelPolinomio1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelIngresoPolinomio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelIngresoPolinomio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panelPolinomio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPolinomio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        panelPolinomio2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPolinomio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPolinomio1ActionPerformed
        // TODO add your handling code here:
        labelPolinomio1.setText(campoPolinomio1.getText());
        campoPolinomio1.setText("");
    }//GEN-LAST:event_botonPolinomio1ActionPerformed

    private void botonIngreso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngreso2ActionPerformed
        // TODO add your handling code here:
        labelPolinomio2.setText(campoPolinomio2.getText());
        campoPolinomio2.setText("");
    }//GEN-LAST:event_botonIngreso2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngreso2;
    private javax.swing.JButton botonPolinomio1;
    private javax.swing.JTextField campoPolinomio1;
    private javax.swing.JTextField campoPolinomio2;
    private javax.swing.JLabel labelPolinomio1;
    private javax.swing.JLabel labelPolinomio2;
    private javax.swing.JLabel labelPolinomioIngreso1;
    private javax.swing.JLabel labelPolinomioIngreso2;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelIngresoPolinomio1;
    private javax.swing.JPanel panelIngresoPolinomio2;
    private javax.swing.JPanel panelPolinomio1;
    private javax.swing.JPanel panelPolinomio2;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
